resources:
- name: app
  type: git
  source:
    uri: https://github.com/waletaiwo/wordpress-demo.git # change this 
    branch: master
    pool:
      branch:
        - master
    trigger: true

- name: terraform-image
  type: git
  source:
    uri: https://github.com/waletaiwo/docker-hub-images.git # change this
    branch: master
    pool:
      branch:
        - master
    trigger: true



jobs:
  - name: terraform-pipe-line
    plan:
    - get: app
    - get: terraform-image

    - task: check-terrafom-version
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform}
        run:
            path: sh
            args: 
                - -exc
                - |
                  terraform --version
    
    - task: run-terraform
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform}
        inputs:
            - name: app        
        run:
            path: sh
            args: 
                - -exc
                - |
                  env
                  ls -lrth
                  cd app
                  ls -lrth
                  terraform init
                  terraform plan
                  terraform apply --auto-approve                             
        params:
          AWS_ACCESS_KEY_ID: ((access-key))
          AWS_SECRET_ACCESS_KEY: ((secret-key))


                
    
    

 
